GridironBulgaria.Web/Controllers/GamesController.cs
namespace GridironBulgaria.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using GridironBulgaria.Web.Services.Games;
    using GridironBulgaria.Web.ViewModels.Games;

    public class GamesController : Controller
    {
        private readonly IGamesService gamesService;

        public GamesController(IGamesService gamesService)
        {
            this.gamesService = gamesService;
        }

        public async Task<IActionResult> Index(string search)
        {
            var allGames = await this.gamesService.GetAllGamesAsync(search);

            return this.View(allGames);
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create(CreateGameViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.gamesService.GameCreateAsync(input);

            return this.RedirectToAction(nameof(this.Index));
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            await this.gamesService.DeleteByIdAsync(id);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            var editViewModel = await this.gamesService.EditGameViewAsync(id);

            return this.View(editViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(EditGameViewModel editInput)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(editInput);
            }

            await this.gamesService.EditGameAsync(editInput);

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Soon()
        {
            return this.View();
        }
    }
}

GridironBulgaria.Web/Controllers/PhotoAlbumsController.cs
namespace GridironBulgaria.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;
    using System.Threading.Tasks;
    using GridironBulgaria.Web.Models;
    using GridironBulgaria.Web.Services.PhotoAlbums;
    using GridironBulgaria.Web.ViewModels.PhotoAlbums;

    public class PhotoAlbumsController : Controller
    {
        private readonly IPhotoAlbumsService photoAlbumsService;

        public PhotoAlbumsController(IPhotoAlbumsService photoAlbumsService)
        {
            this.photoAlbumsService = photoAlbumsService;
        }

        [Route("gallery")]
        public async Task<IActionResult> Index(string search)
        {
            var allTeams = await this.photoAlbumsService.GetAllPhotoAlbumsAsync(search);

            return this.View(allTeams);
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create(CreatePhotoAlbumViewModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            await this.photoAlbumsService.PhotoAlbumCreateAsync(input);

            return this.RedirectToAction(nameof(this.Index));
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            await this.photoAlbumsService.DeleteByIdAsync(id);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            var editViewModel = await this.photoAlbumsService.EditPhotoAlbumViewAsync(id);

            return this.View(editViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(EditPhotoAlbumViewModel editInput)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(editInput);
            }

            await this.photoAlbumsService.EditPhotoAlbumAsync(editInput);

            return this.RedirectToAction(nameof(this.Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GridironBulgaria.Web/Controllers/TeamsController.cs
namespace GridironBulgaria.Web.Controllers
{
    using GridironBulgaria.Web.Models;
    using GridironBulgaria.Web.Services.Teams;
    using GridironBulgaria.Web.ViewModels.Teams;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System.Diagnostics;
    using System.Threading.Tasks;

    public class TeamsController : Controller
    {
        private readonly ITeamsService teamsService;

        public TeamsController(ITeamsService teamsService)
        {
            this.teamsService = teamsService;
        }

        public async Task<IActionResult> Index()
        {
            var allTeams = await this.teamsService.GetAllTeamsAsync();

            return this.View(allTeams);
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Create(CreateTeamInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var teamName = await this.teamsService.CreateAsync(input);

            return this.RedirectToAction(nameof(this.Details), new { name = teamName.ToLower().Replace(' ', '-') });
        }

        [Route("teams/details/{name}")]
        public async Task<IActionResult> Details(string name)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            var teamDetails = await this.teamsService.TeamDetailsAsync(name);

            return this.View(teamDetails);
        }

        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Delete(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            await this.teamsService.DeleteByIdAsync(id);

            return this.RedirectToAction(nameof(this.Index));
        }

        [HttpGet]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            var editViewModel = await this.teamsService.EditTeamViewAsync(id);

            return this.View(editViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdminRole")]
        public async Task<IActionResult> Edit(EditTeamViewModel editInput)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(editInput);
            }

            var teamName = await this.teamsService.EditTeamAsync(editInput);

            return this.RedirectToAction(nameof(this.Details), new { name = teamName.ToLower().Replace(' ', '-') });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GridironBulgaria.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-site-verification" content="3mt5384Wu2j7bUO8nPZ13tOBQLs1C73qofjirVta0ZM" />
    <title>Gridiron Bulgaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/cssGalleryPage/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="apple-touch-icon" sizes="180x180" href="~/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon/favicon-16x16.png">
    <link rel="stylesheet" href="~/css/CustomStyleSheetGridironBG.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid" style="padding-left: 0em; padding-right: 0em;">
                <a class="logo" asp-area="" asp-controller="Home" asp-action="Index"><img class="logo" src="https://i.imgur.com/WNYHe2r.png"></a>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GRIDIRON BULGARIA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav nav-pills flex-grow-1 flex-sm-row-reverse">
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PhotoAlbums" asp-action="Index">Галерия</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index">Отбори</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Мачове</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                    </ul>
                    <div>
                        <a href="https://www.facebook.com/gridironbulgaria/" class="facebookLink" target="_blank"><i id="facebookIcon" class="fab fa-facebook"></i></a>
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <article>
                Copyright &copy; @DateTime.Now.Year | Всички права запазени | Gridiron Bulgaria
            </article>
            <article>
                <a class="githubLink" href="https://github.com/nvgeorgiev/Gridiron-Bulgaria" target="_blank"><i id="githubIcon" class="fab fa-github"></i> Open Source System</a>
            </article>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/cssGalleryPage/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/cssGalleryPage/jquery.slim.min.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/c81a87e6ff.js" crossorigin="anonymous" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>